# Generated by Django 3.2.9 on 2022-02-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
