# Generated by Django 3.2.9 on 2022-06-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='social_funds_per_member',
            new_name='monthly_contribution_per_member',
        ),
        migrations.AddField(
            model_name='config',
            name='no_months_to_pay_0_to_300K',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='config',
            name='no_months_to_pay_300_to_600K',
            field=models.IntegerField(default=6),
        ),
    ]
