# Generated by Django 3.2.9 on 2022-06-12 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrators', '0001_initial'),
        ('members', '0001_initial'),
        ('sessions_', '0002_alter_session_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligatory_Contributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributed', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.administrator')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions_.session')),
            ],
        ),
    ]
