# Generated by Django 3.2.9 on 2022-01-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_', '0001_initial'),
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions_.session'),
        ),
    ]
