# Generated by Django 3.2.9 on 2022-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0004_auto_20220616_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='amount_to_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
