# Generated by Django 3.2.9 on 2022-02-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('refunds', '0002_refund_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='exercise_id',
        ),
        migrations.AddField(
            model_name='refund',
            name='member_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
