# Generated by Django 3.2.9 on 2022-06-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0003_auto_20220612_1857'),
        ('refunds', '0004_remove_refund_borrowing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='borrowing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowings.borrowing'),
        ),
    ]
