# Generated by Django 3.2.9 on 2022-01-29 11:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('type', models.CharField(default='member', max_length=30)),
                ('sex', models.CharField(blank=True, max_length=8)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('avatar', models.ImageField(default='posts/default.jpg', upload_to=users.models.upload_to, verbose_name='Image')),
                ('tel', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
