# Generated by Django 3.2.9 on 2022-01-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing_savings', '0002_borrowing_saving_borrowing_id'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing_saving',
            name='saving_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.saving'),
        ),
    ]
